In [2]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000

In [1]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000

In [2]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000