In [2]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000

In [1]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000

In [2]:
import numpy as np
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Headphones'],
    'Units_Sold': [15, 120, 30, 75, 50],
    'Unit_Price': [1200, 25, 250, 45, 80]
}

df = pd.DataFrame(data)
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']
df

      Product  Units_Sold  Unit_Price  Total_Revenue
0      Laptop          15        1200          18000
1       Mouse         120          25           3000
2     Monitor          30         250           7500
3    Keyboard          75          45           3375
4  Headphones          50          80           4000

In [3]:
print("--- Sales Data Summary Statistics ---")
print(df.describe())

print("\n--- Average Total Revenue ---")
avg_revenue = df['Total_Revenue'].mean()
print(f"The average revenue per product type is: ${avg_revenue:,.2f}")

--- Sales Data Summary Statistics ---
       Units_Sold   Unit_Price  Total_Revenue
count    5.000000     5.000000       5.000000
mean    58.000000   320.000000    7175.000000
std     41.321907   499.887487    6309.467093
min     15.000000    25.000000    3000.000000
25%     30.000000    45.000000    3375.000000
50%     50.000000    80.000000    4000.000000
75%     75.000000   250.000000    7500.000000
max    120.000000  1200.000000   18000.000000

--- Average Total Revenue ---
The average revenue per product type is: $7,175.00

## Team 3 Data Pipeline 
### This notebook demonstrates a collaborative data pipeline developed by group three-student team using Git and GitHub for version control and collaboration. Each team member was responsible for a specific stage of the data workflow, including data generation, analysis, and documentation. The project showcases how multiple contributors can work on different tasks while maintaining a structured and reproducible data science pipeline.

## Data Generation (Student A)
### DataFrame. The dataset includes information such as product names, quantities sold, unit prices, and sales dates. Additional calculations were performed to determine the total revenue generated by each product, providing a foundation for subsequent analysis.

## Data Generation (Student B)
### Student B analyzed the generated dataset by computing key descriptive statistics. This included measures such as mean, median, minimum, maximum, and standard deviation for revenue-related variables. Summary distributions and average revenue metrics were also examined to identify trends and patterns within the sales data.

## Documentation (Student C)
### Student C documented the overall pipeline architecture, workflow, and collaboration process. This included explaining the roles of each team member, outlining the Git and GitHub workflow used for version control, and providing clear descriptions of the dataset, analysis steps, and project structure to ensure reproducibility and ease of understanding.